apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: openim
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
  namespace: openim
type: Opaque
stringData:
  root-username: root
  root-password: RootMongo123!
  app-username: openim
  app-password: OpenIMmongo123!
  database: openim_v3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: openim
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: root-password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: database
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 600m
              memory: 768Mi
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2
        resources:
          requests:
            storage: 5Gi
