-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnuKe86hT3cpcSHgL
t7J4zyfknCEJmivoQfXp2JeIePOgCgYIKoZIzj0DAQehRANCAASzi5Q1Kucyvcn2
4F+ZgX2m/WHbTbrMbrylrZlT96j7tE+OLaONXSG7tNDLQxlTDZtSdoFLE9bUwGV1
ILkB+zXT
-----END PRIVATE KEY-----